apiVersion: v1
kind: Service
metadata:
  labels:
    run: onboard
  name: onboard
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30080
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    run: onboard1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
